// <auto-generated />
namespace MVC_Review_Site_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuickReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuickReview));
        
        string IMigrationMetadata.Id
        {
            get { return "201702122230297_QuickReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
